# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fireimg < Formula
  desc "Upload and delete FireImg images from the command line"
  homepage "https://www.fireimg.com"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.2.0/fireimg_Darwin_x86_64.tar.gz"
      sha256 "1d4073948e537bdeab91278f2ed5ad6f587ac634dc9af3588a94769a1fed25cb"

      def install
        bin.install "fireimg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.2.0/fireimg_Darwin_arm64.tar.gz"
      sha256 "c801d494d3ce1335a864aa6a18142ecf91e412378f43aba64e52f3e4fc2a21e9"

      def install
        bin.install "fireimg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.2.0/fireimg_Linux_x86_64.tar.gz"
      sha256 "b33caedcc5b44a99a8d24997e14f3c9db7e2f9bbc32d3741d57e8c497906420d"
      def install
        bin.install "fireimg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.2.0/fireimg_Linux_arm64.tar.gz"
      sha256 "994a000f71eb490fd6c3cae236140d892e20e6a7ac89a661331b4fa845e89616"
      def install
        bin.install "fireimg"
      end
    end
  end

  test do
    system "#{bin}/fireimg", "version"
  end
end
