# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fireimg < Formula
  desc "Upload and delete FireImg images from the command line"
  homepage "https://www.fireimg.com"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.3.0/fireimg_Darwin_x86_64.tar.gz"
      sha256 "b88f73bfd8f48f5b67bc081df3a173fa15db8e0cdf3226563748c2a39896cdc3"

      def install
        bin.install "fireimg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.3.0/fireimg_Darwin_arm64.tar.gz"
      sha256 "8337aa6c5ee616ca155b68e183d0d569b7bbf190a80677f23b2acd631904ffd2"

      def install
        bin.install "fireimg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.3.0/fireimg_Linux_x86_64.tar.gz"
      sha256 "33ccb215aa03bce59ba5d006ad2e80b09ebda9c8838b5a1fa5b7e32b48b690b2"
      def install
        bin.install "fireimg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.3.0/fireimg_Linux_arm64.tar.gz"
      sha256 "173a0b97408dc22a5b9e26aaca3cbd7d55b2f5b19d9f0a120796cf84a4ffd2bf"
      def install
        bin.install "fireimg"
      end
    end
  end

  test do
    system "#{bin}/fireimg", "version"
  end
end
