# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fireimg < Formula
  desc "Upload and delete FireImg images from the command line"
  homepage "https://www.fireimg.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.1.0/fireimg_Darwin_x86_64.tar.gz"
      sha256 "6277811332766e6d134a642ccf34da96f9dd654edb610bb62b8e566099ac751f"

      def install
        bin.install "fireimg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.1.0/fireimg_Darwin_arm64.tar.gz"
      sha256 "8552368e608dea24deb347805963994acb0cc7f037c23558c78b7707283f9f5f"

      def install
        bin.install "fireimg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.1.0/fireimg_Linux_x86_64.tar.gz"
      sha256 "f0e476ee71fd5c5200cdbb3b4bbc92267a96aaa1a21c6adce1a93d165925c4de"
      def install
        bin.install "fireimg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FirelitStudio/fireimg-cli/releases/download/v0.1.0/fireimg_Linux_arm64.tar.gz"
      sha256 "3bf66bdf28d1d77f308fae5d0181d8a512d59dd8312b3f16d69decf6d26126e9"
      def install
        bin.install "fireimg"
      end
    end
  end

  test do
    system "#{bin}/fireimg", "version"
  end
end
